language: rust
cache: cargo

branches:
  only:
    - master

rust:
  - 1.35.0
  - stable

os:
  - linux
  - osx
  - windows

env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-D warnings"

matrix:
  fast_finish: true
  allow_failures:
    # Travis CI's Windows tier is presently beta (slow / unreliable)
    - os: windows

install:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt --all -- --check
  - cargo clippy --all
  - cargo build --release
  - cargo test --release
  - cargo doc --no-deps
